# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'plasma/kwin': '@same'
    'third-party/wayland': '@latest'
    'third-party/wayland-protocols': '@latest'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
